### ISSUE TITLE
regarding mower

### ISSUE THREAD

**Issue by ritviksahajpal** [perrygeo/mower#2]
@perrygeo thanks for creating this package, it looks really useful! May I ask if this is still under development and if you recommend it be used since it has not been updated for a while. thanks!

**Comment by perrygeo** [comment]
It is not under active development. I have no plans to continue working it and wouldn't recommend it for any production use. However, if you or anyone else would like to take ownership and continue, I would encourage you to fork the project.

Thanks for the reminder @ritviksahajpal - I'll archive the project to make the status clear.
